# Generated by Django 2.0.7 on 2018-07-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payam', '0002_auto_20180713_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payam',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
