# Generated by Django 2.0.7 on 2018-07-18 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('privatepayam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private',
            name='dest',
        ),
        migrations.AddField(
            model_name='private',
            name='dest',
            field=models.ManyToManyField(related_name='maghsad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='private',
            name='owner',
        ),
        migrations.AddField(
            model_name='private',
            name='owner',
            field=models.ManyToManyField(related_name='saheb', to=settings.AUTH_USER_MODEL),
        ),
    ]
