# Generated by Django 2.0.7 on 2018-07-18 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('privatepayam', '0002_auto_20180718_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private',
            name='dest',
        ),
        migrations.AddField(
            model_name='private',
            name='dest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maghsad', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='private',
            name='owner',
        ),
        migrations.AddField(
            model_name='private',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saheb', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
