# Generated by Django 2.0.7 on 2018-07-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatepayam', '0003_auto_20180718_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='private',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
