# Generated by Django 2.0.7 on 2018-07-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_users_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
