# Generated by Django 2.0.7 on 2018-07-17 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_users_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='is_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
