# Generated by Django 2.0.7 on 2018-07-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_users_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='color',
            field=models.CharField(default=555555, max_length=120),
            preserve_default=False,
        ),
    ]
