# Generated by Django 2.0.7 on 2018-07-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_users_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='color',
        ),
    ]
