# Generated by Django 2.0.7 on 2018-07-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_users_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='color',
            field=models.CharField(default='a80000', max_length=120),
        ),
    ]
